name: itoju_mobile
description: "Health tracker Mobile!"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  # google_fonts: ^6.1.0
  dio: ^5.4.1
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.6.1
  another_flushbar: ^1.12.30
  flutter_spinkit: ^5.2.1
  image_picker: ^1.0.4
  local_auth: ^2.1.8
  pinput: ^3.0.1
  # google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  intl: ^0.19.0
  firebase_storage: ^11.6.8
  google_sign_in: ^6.2.1
  # sign_in_with_apple: ^5.0.0
  cloud_firestore: ^4.15.7
  persistent_bottom_nav_bar_v2: ^4.2.8
  flutter_svg: ^2.0.10+1
  flutter_facebook_auth: ^6.1.1
  fast_cached_network_image: ^1.2.7
  webview_flutter: ^4.7.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  sticky_headers: ^0.3.0+2
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "asset/png/itojuicon.png"
  adaptive_icon_background: "#ffffff"
  background_color_ios: "#ffffff"

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - asset/icons/
    - asset/png/
    - asset/svg/
    - asset/avatars/
    - asset/fonts/

  fonts:
    - family: Axiforma
      fonts:
        - asset: asset/fonts/Axiforma.otf
